### ISSUE TITLE
Depends on libncurses too

### ISSUE THREAD

**Issue by MustBeArt** [phase4ground/ka9q-sdr#2]
On Raspbian I had to

sudo apt-get install libncurses5-dev

to satisfy a dependency on ncurses.h found in display.c

**Comment by jschiefer** [comment]
I just merged a change that adds libncurses5-dev as a dependency in the former dependency file, which I renamed to [INSTALLING.md](../blob/master/INSTALLING.md) in #3.

Could you please verify whether these instructions are now correct for Raspbian?

**Comment by ka9q** [comment]
I've added that to the documentation. I suggest installing both libncurses5-dev and libncursesw5-dev. The latter supports 'wide' (Unicode) characters, which I use in a few help files to display graphics for special keyboard keys, e.g., in the 'monitor' program.
