### ISSUE TITLE
Failed to build on Ubuntu 16.04 and Debian 8 (Jessie)

### ISSUE THREAD

**Issue by sconklin** [phase4ground/ka9q-sdr#4]
I tried to build on 16.04 and ran into the problem with an older libfftw3-dev version.

I downloaded the tarball for that and ran ./configure;make;make install, but it didn't resolve the issue.

**Comment by Abraxas3d** [comment]
Any progress on this? What can I do to help fix it?

**Comment by ka9q** [comment]
I'm closing this for now, but I would like to add the minimum required Ubuntu version to the documentation if somebody can easily find out for me.
